Repository atlp-rwanda/tech-strikers-bn-backend, pull requests merged in 2020-12, with the labels that each got.

#30 #175974127 It sets up github Actions as CI Tool
  .env.example
  .github/workflows/nodejs.yml
  .nycrc
  .sequelizerc
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/database/config/config.js
  src/database/migrations/20201118122004-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20201118193101-User.js
  src/index.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/api/users.route.js
  src/routes/index.js
  src/services/index.js
  src/services/user.service.js
  src/utils/customMessage.js
  src/utils/email.js
  src/utils/helpers.js
  src/utils/index.js
  src/utils/responses.js
  src/utils/statusCode.js
  swagger.json
  test/controllers/user.test.js
  test/data/user.mock.js
  test/initial.test.js
  test/welcome/initial.test.js
Labels: Ready For Review, enhancement

#24 #175636840 Generate jwt once a user signed up successfully
  package-lock.json
  package.json
  src/database/models/index.js
  src/index.js
  src/middleWares/auth.js
  src/middleWares/index.js
  src/routes/api/users.js
  src/utils/util.jwt.js
  test/initial.test.js
Labels: Ready For Review

#23 #175636841 Send verification Email on signup
  .eslintrc.json
  .github/workflows/nodejs.yml
  .gitignore
  .travis.yml
  package.json
  src/controllers/user.controller.js
  src/database/models/index.js
  src/index.js
  src/middleWares/index.js
  src/middlewares/auth.js
  src/middlewares/tokenAuthentication.js
  src/routes/api/users.js
  src/routes/api/users.route.js
  src/routes/index.js
  src/services/user.service.js
  src/utils/customMessage.js
  src/utils/email.js
  src/utils/responses.js
  src/utils/util.jwt.js
  test/controllers/user.test.js
  test/data/user.mock.js
  test/initial.test.js
  test/welcome/api.test.js
  test/welcome/initial.test.js
Labels: Ready For Review

#21 #175636777 Support of multiple languages
  .eslintrc.json
  locales/en.json
  locales/fr.json
  locales/ki.json
  package-lock.json
  package.json
  src/index.js
  src/utils/i18n.js
  test/i18n.test.js
Labels: Ready For Review, Rebase

#22 175636844 Social media auth
  .env.example
  .eslintrc.json
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
  src/config/passport.js
  src/controllers/auth.controller.js
  src/database/config/config.js
  src/database/migrations/20201118122004-create-user.js
  src/database/models/index.js
  src/database/models/notification.js
  src/database/models/user.js
  src/index.js
  src/routes/api/index.js
  src/routes/api/users.route.js
  src/routes/index.js
  src/services/auth.service.js
  src/utils/helpers.js
  swagger.json
  test/controllers/auth.test.js
  test/controllers/initial.test.js
Labels: Ready For Review, enhancement

#27 #17563684 Login User and Generate a Token When Password is Excluded
  .github/workflows/nodejs.yml
  .gitignore
  locales/en.json
  locales/fr.json
  locales/ki.json
  package-lock.json
  package.json
  src/controllers/login.controller.js
  src/database/migrations/20201118122004-create-user.js
  src/database/models/index.js
  src/database/models/notification.js
  src/database/models/user.js
  src/database/seeders/20201118193101-User.js
  src/index.js
  src/routes/api/users.js
  src/routes/api/users.route.js
  src/utils/hash.js
  src/utils/helpers.js
  src/utils/index.js
  src/validation/index.js
  test/controllers/initial.test.js
  test/controllers/login.test.js
  test/controllers/user.test.js
  test/welcome/initial.test.js
Labels: Ready For Review

#29 #175636847 Add routes for getting and updating profile information
  locales/en.json
  locales/fr.json
  locales/ki.json
  package-lock.json
  package.json
  src/controllers/login.controller.js
  src/controllers/user.controller.js
  src/database/migrations/20201222145104-create-user.js
  src/database/models/user.js
  src/database/seeders/20201118193101-User.js
  src/index.js
  src/middlewares/multer.js
  src/middlewares/tokenAuthentication.js
  src/routes/api/index.js
  src/routes/api/users.route.js
  src/services/user.service.js
  src/utils/cloudinary.js
  src/utils/helpers.js
  src/utils/index.js
  src/utils/util.jwt.js
  src/validation/login.validation.js
  swagger.json
  test/controllers/initial.test.js
  test/controllers/login.test.js
  test/controllers/user.test.js
  test/data/user.mock.js
  test/welcome/initial.test.js
Labels: Ready For Review
